apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: o0blmcqsq-python 
  janus-idp.io/tekton: o0blmcqsq-python
  backstage.io/kubernetes-id: o0blmcqsq-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o0blmcqsq-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  